package com.example.notifybridge.core.common

import java.util.Locale

object LocalizedText {
    private fun zh() = Locale.getDefault().language.startsWith("zh")

    fun forwardingDisabled() = if (zh()) "转发总开关未开启" else "Forwarding is disabled"
    fun systemExcluded() = if (zh()) "系统通知已排除" else "System notifications are excluded"
    fun ongoingExcluded() = if (zh()) "ongoing 通知已排除" else "Ongoing notifications are excluded"
    fun emptyBodyExcluded() = if (zh()) "空正文通知已排除" else "Empty-body notifications are excluded"
    fun packageBlacklistHit() = if (zh()) "命中包名黑名单" else "Matched blocked package list"
    fun channelLoopPrevented(channelName: String) = if (zh()) "已阻止 $channelName 渠道回环通知" else "Blocked $channelName channel loop notification"
    fun packageWhitelistMiss() = if (zh()) "未命中包名白名单" else "Did not match allowed package list"
    fun keywordBlacklistHit() = if (zh()) "命中关键词黑名单" else "Matched keyword blacklist"
    fun keywordWhitelistMiss() = if (zh()) "未命中关键词白名单" else "Did not match keyword whitelist"
    fun dedupeWindowHit() = if (zh()) "命中去重时间窗口" else "Matched dedupe window"

    fun endpointNotConfigured() = if (zh()) "当前转发渠道未配置完整" else "The current delivery channel is not fully configured"
    fun networkUnavailable() = if (zh()) "网络不可用" else "Network unavailable"
    fun timeout() = if (zh()) "请求超时" else "Request timed out"
    fun serializationFailed() = if (zh()) "序列化失败" else "Serialization failed"
    fun connectionFailed() = if (zh()) "连接失败" else "Connection failed"
    fun unknownError() = if (zh()) "未知错误" else "Unknown error"
    fun noBody() = if (zh()) "(无正文)" else "(No body)"

    fun authFailureCategory() = if (zh()) "鉴权失败" else "Auth failure"
    fun authFailureSummary() = if (zh()) "服务端拒绝了当前认证信息。" else "The server rejected the current authentication."
    fun authFailureSuggestion() = if (zh()) "检查 Bearer Token 是否过期，或确认服务端是否要求额外 Header。" else "Check whether the Bearer token expired or the server expects extra headers."
    fun notFoundCategory() = if (zh()) "地址不存在" else "Endpoint not found"
    fun notFoundSummary() = if (zh()) "Webhook 地址返回 404，服务端路由可能不存在。" else "The webhook returned 404 and the route may not exist."
    fun notFoundSuggestion() = if (zh()) "检查 Settings 里的 Webhook URL 是否正确，尤其是路径和末尾斜杠。" else "Verify the webhook URL in Settings, especially its path and trailing slash."
    fun timeoutCategory() = if (zh()) "请求超时" else "Timeout"
    fun timeoutSummary() = if (zh()) "请求没有在预期时间内完成。" else "The request did not finish in time."
    fun timeoutSuggestion() = if (zh()) "先确认网络质量，再检查服务端是否处理过慢；这类错误通常适合重试。" else "Check network quality and server latency; this kind of error is usually retryable."
    fun rateLimitCategory() = if (zh()) "被服务端限流" else "Rate limited"
    fun rateLimitSummary() = if (zh()) "服务端认为请求过于频繁，暂时拒绝处理。" else "The server temporarily rejected the request because it was too frequent."
    fun rateLimitSuggestion() = if (zh()) "稍后再试，并考虑在服务端或客户端增加节流策略。" else "Retry later and consider adding throttling on the client or server."
    fun serverErrorCategory() = if (zh()) "服务端异常" else "Server error"
    fun serverErrorSummary() = if (zh()) "Webhook 服务端返回了 5xx 错误。" else "The webhook server returned a 5xx error."
    fun serverErrorSuggestion() = if (zh()) "优先检查服务端日志；客户端可以继续自动重试。" else "Check server logs first; the client can keep retrying."
    fun clientErrorCategory() = if (zh()) "请求参数异常" else "Client request error"
    fun clientErrorSummary() = if (zh()) "服务端返回 4xx，说明当前请求不符合接口要求。" else "The server returned 4xx, which means the request does not match the API contract."
    fun clientErrorSuggestion() = if (zh()) "检查服务端对 JSON 字段、Header 和认证方式的要求。" else "Review the server requirements for JSON fields, headers, and auth."
    fun endpointCategory() = if (zh()) "未配置端点" else "Endpoint missing"
    fun endpointSummary() = if (zh()) "当前没有可用的 Webhook 地址。" else "There is no usable webhook endpoint configured."
    fun endpointSuggestion() = if (zh()) "先在 Settings 里填写 Webhook URL，再重新测试发送。" else "Fill in the webhook URL in Settings first, then retry the test."
    fun networkCategory() = if (zh()) "网络不可用" else "Network unavailable"
    fun networkSummary() = if (zh()) "设备当前没有可用网络，发送无法开始。" else "The device has no available network, so sending cannot start."
    fun networkSuggestion() = if (zh()) "确认设备联网状态，必要时关闭省电限制后再试。" else "Confirm the device is online and try again after relaxing battery restrictions if needed."
    fun dnsCategory() = if (zh()) "连接或 DNS 失败" else "Connection or DNS failure"
    fun dnsSummary() = if (zh()) "请求没有成功建立到目标服务端的连接。" else "The request failed to establish a connection to the target server."
    fun dnsSuggestion() = if (zh()) "检查域名解析、证书、端口和代理设置；若地址是内网，也要确认设备可达。" else "Check DNS, certificates, ports, and proxy settings; if it is an intranet address, make sure the device can reach it."
    fun serializationCategory() = if (zh()) "序列化失败" else "Serialization failure"
    fun serializationSummary() = if (zh()) "客户端在构造或解析请求数据时发生异常。" else "The client failed while building or parsing request data."
    fun serializationSuggestion() = if (zh()) "优先检查本地 payload 结构和服务端字段约定，这类错误通常不适合盲目重试。" else "Check the local payload structure and server field contract; blind retries usually do not help."
    fun unknownCategory() = if (zh()) "未知异常" else "Unknown error"
    fun unknownSummary(errorMessage: String?) = errorMessage ?: if (zh()) "发送失败，但没有更多上下文。" else "Sending failed without more context."
    fun unknownSuggestion() = if (zh()) "先查看本页的请求 payload 和尝试历史，再结合服务端日志排查。" else "Inspect the payload and attempt history first, then correlate with server logs."
}
